# Generated by Django 2.1.7 on 2019-04-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190411_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default=88007773333, max_length=50),
            preserve_default=False,
        ),
    ]
