# Generated by Django 2.1.7 on 2019-05-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
