# Generated by Django 2.1.7 on 2019-05-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_client_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundry',
            old_name='adress',
            new_name='address',
        ),
    ]
