# Generated by Django 2.1.7 on 2019-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190512_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_payment',
            field=models.DateField(null=True),
        ),
    ]
